/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sv.edu.INIM.guia5poo1.ejerciciosComplementario;

import sv.edu.INIM.guia5poo1.FormularioPOO1;
import sv.edu.INIM.guia5poo1.Main;
import sv.edu.INIM.guia5poo1.RadioButton;
import sv.edu.INIM.guia5poo1.jComboBox;
import sv.edu.INIM.guia5poo1.mdi.Logueo;

/**
 *
 * @author Gilamr Lobos && Ernesto Zeledon
 */
public class ejercicioComplementario extends javax.swing.JFrame {

    /**
     * Creates new form ejercicioComplementario
     */
    public ejercicioComplementario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        openMenuItem = new javax.swing.JMenuItem();
        saveMenuItem = new javax.swing.JMenuItem();
        saveAsMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        contentMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        FormularioPOO1MenuItem = new javax.swing.JMenuItem();
        MainMenuItem = new javax.swing.JMenuItem();
        RadioButtonMenuItem = new javax.swing.JMenuItem();
        jComboBoxMenuItem = new javax.swing.JMenuItem();
        LogueoMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fileMenu.setMnemonic('f');
        fileMenu.setText("File");

        openMenuItem.setMnemonic('o');
        openMenuItem.setText("Open");
        fileMenu.add(openMenuItem);

        saveMenuItem.setMnemonic('s');
        saveMenuItem.setText("Save");
        fileMenu.add(saveMenuItem);

        saveAsMenuItem.setMnemonic('a');
        saveAsMenuItem.setText("Save As ...");
        saveAsMenuItem.setDisplayedMnemonicIndex(5);
        fileMenu.add(saveAsMenuItem);

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Internal Frames");

        contentMenuItem.setMnemonic('c');
        contentMenuItem.setText("Imagenes");
        contentMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contentMenuItemActionPerformed(evt);
            }
        });
        helpMenu.add(contentMenuItem);

        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("Matematicas");
        aboutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutMenuItemActionPerformed(evt);
            }
        });
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        editMenu.setMnemonic('e');
        editMenu.setText("Otros Ejercicios");

        FormularioPOO1MenuItem.setMnemonic('t');
        FormularioPOO1MenuItem.setText("FormularioPOO1");
        FormularioPOO1MenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FormularioPOO1MenuItemActionPerformed(evt);
            }
        });
        editMenu.add(FormularioPOO1MenuItem);

        MainMenuItem.setMnemonic('y');
        MainMenuItem.setText("Main");
        MainMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MainMenuItemActionPerformed(evt);
            }
        });
        editMenu.add(MainMenuItem);

        RadioButtonMenuItem.setMnemonic('p');
        RadioButtonMenuItem.setText("RadioButton");
        RadioButtonMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButtonMenuItemActionPerformed(evt);
            }
        });
        editMenu.add(RadioButtonMenuItem);

        jComboBoxMenuItem.setMnemonic('d');
        jComboBoxMenuItem.setText("jComboBox");
        jComboBoxMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxMenuItemActionPerformed(evt);
            }
        });
        editMenu.add(jComboBoxMenuItem);

        LogueoMenuItem.setText("Logueo");
        LogueoMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogueoMenuItemActionPerformed(evt);
            }
        });
        editMenu.add(LogueoMenuItem);

        menuBar.add(editMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void FormularioPOO1MenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FormularioPOO1MenuItemActionPerformed
        // TODO add your handling code here:
        FormularioPOO1 f1 = new FormularioPOO1();
        f1.setVisible(true);
        
    }//GEN-LAST:event_FormularioPOO1MenuItemActionPerformed
   
    private void MainMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MainMenuItemActionPerformed
        // TODO add your handling code here:
        Main m = new Main();
        m.setVisible(true);
    }//GEN-LAST:event_MainMenuItemActionPerformed

    private void RadioButtonMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButtonMenuItemActionPerformed
        // TODO add your handling code here:
        RadioButton rbtn = new RadioButton();
        rbtn.setVisible(true);
    }//GEN-LAST:event_RadioButtonMenuItemActionPerformed

    private void jComboBoxMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxMenuItemActionPerformed
        // TODO add your handling code here:
        jComboBox jcbox = new jComboBox();
        jcbox.setVisible(true);
    }//GEN-LAST:event_jComboBoxMenuItemActionPerformed

    private void LogueoMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogueoMenuItemActionPerformed
        // TODO add your handling code here:
        Logueo lg = new Logueo();
        lg.setVisible(true);
    }//GEN-LAST:event_LogueoMenuItemActionPerformed
    //Añadir internal jframe
    /*
    Esto es una prueba para saber si github detecta los cambios de que he hecho 
    esto 
    esto 
    esto
    esto
    esto
    
    */
    
    private void contentMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contentMenuItemActionPerformed
        // TODO add your handling code here:
        Imagenes imgs = new Imagenes();
        desktopPane.add(imgs);
        imgs.setVisible(true);
    }//GEN-LAST:event_contentMenuItemActionPerformed

    private void aboutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutMenuItemActionPerformed
        // TODO add your handling code here:
        Matematicas mate = new Matematicas();
        desktopPane.add(mate);
        mate.setVisible(true);
    }//GEN-LAST:event_aboutMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ejercicioComplementario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ejercicioComplementario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ejercicioComplementario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ejercicioComplementario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ejercicioComplementario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem FormularioPOO1MenuItem;
    private javax.swing.JMenuItem LogueoMenuItem;
    private javax.swing.JMenuItem MainMenuItem;
    private javax.swing.JMenuItem RadioButtonMenuItem;
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JMenuItem contentMenuItem;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenuItem jComboBoxMenuItem;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem openMenuItem;
    private javax.swing.JMenuItem saveAsMenuItem;
    private javax.swing.JMenuItem saveMenuItem;
    // End of variables declaration//GEN-END:variables

}
